networks:
  kind:
  rest:

volumes:
  docker-certs-ca:
  docker-certs-client:
  docker-socket:

services:
  daemon:
    image: docker:dind
    privileged: true
    restart: on-failure:5
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - docker-socket:/var/run
    networks:
      kind:
        aliases:
          - docker

  kathara-rest:
    image: ghcr.io/uniba-ktr/kaas-kathara-rest:latest
    depends_on:
      - daemon
    environment:
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_HOST=tcp://docker:2376
    volumes:
      - docker-certs-client:/certs/client:ro
    networks:
      - kind
      - rest
    ports:
      - 8000:8000

  web-tty:
    image: ghcr.io/uniba-ktr/kaas-web-tty:latest
    depends_on:
      - daemon
    restart: on-failure
    ports:
      - 8001:8080
    networks:
      - kind
      - rest
    environment:
      - WEB_TTY_DEBUG=false
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_HOST=tcp://docker:2376
    volumes:
      - docker-certs-client:/certs/client:ro

  kathara-ui:
    image: ghcr.io/uniba-ktr/kaas-kathara-ui-vue3:latest
    ports:
      - 8080:8080
    networks:
      - rest

  kathara-traefik:
    image: traefik
    command:
      - "--log.level=DEBUG"
    environment:
      - TZ=${TIME_ZONE:-Europe/Berlin}
    volumes:
      - docker-certs-client:/certs/client:ro
    ports:
      - 80:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.https-redirect.entrypoints=web"
      - "traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.https-redirect.middlewares=https-redirect"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-https.entrypoints=websecure"
      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.routers.traefik-https.tls.certresolver=ktr-letsencrypt"
      - "traefik.http.routers.traefik-https.rule=Host(`traefik.ktr.uni-bamberg.de`, `traefik.ktr.wiai.uni-bamberg.de`)"
      - "traefik.http.routers.traefik-https.service=api@internal"
      - "traefik.http.routers.traefik-https.middlewares=ktr-whitelist@file,ktr-rw@file,ktr-auth@file"
      - "com.centurylinklabs.watchtower.enable=true"


