networks:
  kind:
  rest:

volumes:
  docker-certs-ca:
  docker-certs-client:
  docker-socket:

# iptable upgrades, run the following on your host:
# -> sudo modprobe ip6table_filter
services:
  daemon:
    image: docker:23-dind
    privileged: true
    restart: on-failure:5
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - docker-socket:/var/run
    networks:
      kind:
        aliases:
          - docker

  kathara-rest:
    image: ghcr.io/uniba-ktr/kaas-kathara-rest:latest
    depends_on:
      - daemon
    environment:
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_HOST=tcp://docker:2376
    volumes:
      - docker-certs-client:/certs/client:ro
    networks:
      - kind
      - rest
    ports:
      - 8000:8000

  web-tty:
    image: ghcr.io/uniba-ktr/kaas-web-tty:latest
    depends_on:
      - daemon
    restart: on-failure
    ports:
      - 8001:8080
    networks:
      - kind
      - rest
    environment:
      - WEB_TTY_DEBUG=false
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_HOST=tcp://docker:2376
    volumes:
      - docker-certs-client:/certs/client:ro

  kathara-ui:
    image: ghcr.io/uniba-ktr/kaas-kathara-ui-vue3:latest
    ports:
      - 8080:8080
    networks:
      - rest
