# generated by datamodel-codegen:
#   filename:  message.json
#   timestamp: 2022-07-25T08:43:39+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Extra

from src.model.enumerations import LabStatus


class Message(BaseModel):
    class Config:
        extra = Extra.forbid

    lab_name: str
    lab_hash: Optional[str] = None
    lab_status: Optional[LabStatus] = None
    success: Optional[bool] = None
    info: Optional[Dict[str, Any]] = None
